# Generated by Django 4.1 on 2022-08-22 03:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=30, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=30, verbose_name="Last Name"),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("about", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(unique=True)),
                ("website", models.URLField()),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email Address"
                    ),
                ),
                ("address", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=50, unique=True)),
                ("description", models.TextField()),
                ("date_published", models.DateField()),
                ("isbn", models.PositiveIntegerField(verbose_name="ISBN")),
                (
                    "page_count",
                    models.PositiveIntegerField(verbose_name="Number of pages"),
                ),
                (
                    "authors",
                    models.ManyToManyField(related_name="authors", to="books.author"),
                ),
                (
                    "publishers",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="books.publisher",
                    ),
                ),
            ],
            options={
                "ordering": ("-date_published",),
            },
        ),
    ]
