# Generated by Django 4.1 on 2022-08-23 09:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="subscribers",
            field=models.ManyToManyField(
                related_name="subcribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
