# Generated by Django 4.1 on 2022-08-24 00:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_publisher_subscribers"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="slug",
            field=models.SlugField(default="author-slug", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="publisher",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subcribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
