# Generated by Django 4.1 on 2022-08-24 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0003_author_slug_alter_publisher_subscribers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(
                error_messages={"unique": "A book with this ISBN already exists"},
                max_length=13,
                unique=True,
                verbose_name="ISBN",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="publishers",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="books.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True, related_name="subscribers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
