# Generated by Django 4.1 on 2022-08-24 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_isbn_alter_book_publishers_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="publishers",
            new_name="publisher",
        ),
    ]
