# Generated by Django 4.1 on 2022-08-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0006_alter_book_publisher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="about",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_published",
                to="books.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(
                error_messages={"unique": "A book with this title already exists."},
                max_length=50,
                unique=True,
            ),
        ),
    ]
