# Generated by Django 4.1 on 2022-08-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_alter_author_about_alter_book_publisher_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-date_published"]},
        ),
        migrations.AlterModelOptions(
            name="publisher",
            options={"ordering": ["name"]},
        ),
        migrations.AlterField(
            model_name="author",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email address"),
        ),
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books_written", to="books.author"
            ),
        ),
        migrations.AlterField(
            model_name="publisher",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Email Address"),
        ),
    ]
