# Generated by Django 4.1 on 2022-08-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0012_alter_book_publisher"),
        ("books", "0013_alter_book_options_alter_publisher_options_and_more"),
    ]

    operations = []
