# Generated by Django 4.1 on 2022-08-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0014_merge_20220829_0255"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True, related_name="books_written", to="books.author"
            ),
        ),
    ]
