# Generated by Django 4.1 on 2022-08-29 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0015_alter_book_authors"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="description",
            new_name="summary",
        ),
    ]
