# Generated by Django 4.1 on 2022-08-31 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0017_alter_author_about_alter_author_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, default=49.99, max_digits=5),
        ),
        migrations.AddField(
            model_name="book",
            name="purchase_link",
            field=models.URLField(default="https://amazon.com"),
        ),
        migrations.AddField(
            model_name="book",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
