# Generated by Django 4.1 on 2022-09-07 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0018_book_price_book_purchase_link_book_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="author",
            name="about",
        ),
    ]
