# Generated by Django 4.1 on 2022-09-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0019_remove_author_about"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publisher",
            name="name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
