# Generated by Django 4.1 on 2022-09-12 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0020_alter_publisher_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                related_name="books_written", to="books.author"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books_published",
                to="books.publisher",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="purchase_link",
            field=models.URLField(),
        ),
    ]
