# Generated by Django 4.1 on 2022-08-23 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_publisher_subscribers"),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="bookmark",
            field=models.ManyToManyField(related_name="bookmark", to="books.book"),
        ),
    ]
