# Generated by Django 4.0 on 2022-10-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0024_author_subscribers_alter_publisher_subscribers'),
        ('accounts', '0005_alter_myuser_bookmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='bookmark',
            field=models.ManyToManyField(blank=True, related_name='bookmark', to='books.Book'),
        ),
    ]
